<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;

/**
 * Regenerate the harmonic-fragments constant file from the DB.
 *
 * Reads all progressions from sbn_chord_progressions (including
 * alt_numerals variants), normalizes numeral tokens, and writes
 * storage/app/harmonic-fragments.generated.php as a PHP return array.
 *
 * The generated file is committed to git and loaded at runtime by
 * HarmonicPatternMatcher with zero DB access.
 */
class ReseedFragments extends Command
{
    protected $signature = 'sbn:reseed-fragments';

    protected $description = 'Regenerate storage/app/harmonic-fragments.generated.php from sbn_chord_progressions';

    public function handle(): int
    {
        $progressions = DB::table('sbn_chord_progressions')
            ->select('id', 'numerals', 'alt_numerals')
            ->orderBy('sort_order')
            ->orderBy('id')
            ->get();

        $fragments = [];

        foreach ($progressions as $prog) {
            // Canonical entry
            $canonicalTokens = $this->parseAndNormalize($prog->numerals);
            if (count($canonicalTokens) >= 2) {
                $fragments[] = [
                    'id'            => (int) $prog->id,
                    'numerals'      => $canonicalTokens,
                    'variant_index' => null,
                    'variant_label' => null,
                ];
            }

            // Variant entries
            if ($prog->alt_numerals) {
                $variants = is_string($prog->alt_numerals)
                    ? json_decode($prog->alt_numerals, true)
                    : $prog->alt_numerals;

                if (is_array($variants)) {
                    foreach ($variants as $vi => $variant) {
                        $variantTokens = $this->parseAndNormalize($variant['numerals'] ?? '');
                        if (count($variantTokens) >= 2) {
                            $fragments[] = [
                                'id'            => (int) $prog->id,
                                'numerals'      => $variantTokens,
                                'variant_index' => $vi,
                                'variant_label' => $variant['label'] ?? null,
                            ];
                        }
                    }
                }
            }
        }

        $this->info('Flattened ' . count($progressions) . ' progressions → ' . count($fragments) . ' fragments');

        // Generate PHP file
        $export = $this->exportArray($fragments);
        $content = "<?php\n\n// Auto-generated by sbn:reseed-fragments at " . now()->toIso8601String() . "\n// DO NOT EDIT MANUALLY — run php artisan sbn:reseed-fragments to regenerate.\n\nreturn {$export};\n";

        $path = storage_path('app/harmonic-fragments.generated.php');
        File::ensureDirectoryExists(dirname($path));
        File::put($path, $content);

        $this->info('Wrote ' . $path . ' (' . strlen($content) . ' bytes)');

        return self::SUCCESS;
    }

    /**
     * Parse a comma-separated numeral string and normalize tokens.
     *
     * Normalization: dim7 → o7, °7 → o7, trim whitespace.
     *
     * @return array<int, string>
     */
    private function parseAndNormalize(string $numeralsStr): array
    {
        $tokens = array_values(array_filter(array_map('trim', explode(',', $numeralsStr))));

        return array_map(function (string $t): string {
            $t = str_replace('°7', 'o7', $t);
            $t = preg_replace('/dim7$/i', 'o7', $t);
            return $t;
        }, $tokens);
    }

    /**
     * Export a PHP array as a string with readable formatting.
     *
     * @return string
     */
    private function exportArray(array $data): string
    {
        $lines = ["[\n"];
        foreach ($data as $i => $item) {
            $lines[] = "    {$i} => [\n";
            $lines[] = "        'id'            => {$item['id']},\n";
            $lines[] = "        'numerals'      => " . var_export($item['numerals'], true) . ",\n";
            $lines[] = "        'variant_index' => " . var_export($item['variant_index'], true) . ",\n";
            $lines[] = "        'variant_label' => " . var_export($item['variant_label'], true) . ",\n";
            $lines[] = "    ],\n";
        }
        $lines[] = "]";
        return implode('', $lines);
    }
}
