<?php

return [
    'the-girl-from-ipanema' => [
        'title' => 'The Girl From Ipanema',
        'shortTitle' => 'Girl from Ipanema',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/5.webp',
        'description' => "Without a doubt the most famous Bossa Nova song of all time — and one of the most recorded songs in history. Written by Tom Jobim and Vinícius de Moraes in 1962, it became a worldwide hit through the legendary <em>Getz/Gilberto</em> recording of 1964, featuring <strong>João Gilberto's</strong> fingerstyle guitar and <strong>Astrud Gilberto's</strong> unforgettable vocal.",
        'recordings' => '822 Recordings',
        'voicingName' => 'Key Chords',
        'voicingSlug' => 'maj6-custom-roote-inv2-9',
        'rootOverride' => 'Db',
        'voicingCaption' => "The <strong>Dbmaj6(9)</strong> with 5th (Ab) in the bass opens the song. Unlike traditional chords, this chord is voiced on 4ths, giving it a more open sound.",
        'progressionName' => 'Ellington Progression',
        'progressionLibrarySlug' => 'ellington-progression',
        'progressionSeedKey' => 'F',
        'progressionCaption' => "<strong>Tom Jobim</strong> borrowed the idea of leaping from the <strong>I</strong> chord to the <strong>II7</strong> from <strong>Duke Ellington's</strong> <em>Take the A-Train</em>. A favourite Jobim move that reappears across his catalogue.",
        'progressionSlugs' => ['maj6-custom-roote-inv2-9-overAb', 'dom7-shell-roota-9'],
        // Live leadsheet bars — replaces progressionTiles in the SyncedPlayer panel
        'syncedPlayer' => ['slug' => 'the-girl-from-ipanema', 'start' => 5, 'end' => 12],
        'rhythmName' => 'Trademark Rhythm Pattern',
        'rhythmSlug' => 'gilberto-rhythm',
        'rhythmCaption' => "The classic Gilberto pattern has three accents. The thumb handles the bass on beat 1 and 3, the fingers pluck  the upper strings.",
        'rhythmCitation' => "<strong>Stan Getz & João Gilberto</strong>, <em>Getz / Gilberto</em>, 1964",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Ten essential Bossa Nova guitar chords with voicing diagrams, practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ]
    ],
    'manha-de-carnaval' => [
        'title' => 'Manhã de Carnaval',
        'shortTitle' => 'Manhã de Carnaval',
        'artist' => 'Luiz Bonfá',
        'image' => '/images/top10/bossa-nova-songs/7.webp',
        'description' => "<strong>Luiz Bonfá</strong> composed this theme for the 1959 film <em>Black Orpheus</em> (<em>Orfeu Negro</em>) and it became one of the most beloved Brazilian melodies ever written. The song is a touchstone for solo guitar — famously reimagined by <strong>Paco de Lucía</strong>, <strong>John McLaughlin</strong>, and <strong>Al Di Meola</strong> on their 1980 live recording <em>Friday Night in San Francisco</em>. Here we feature <strong>Bonfá's own original recording</strong>, which captures the song in its purest, most intimate form.",
        'recordings' => '706 Recordings',
        'voicingName' => 'Key Chords',
        'voicingSlug' => 'dom7-archetype-roota',
        'rootOverride' => 'E',
        'voicingCaption' => "This <strong>E7</strong> is an all-star guitar voicing used in Blues, Jazz, Pop and Bossa Nova.",
        'progressionName' => 'Perfect Authentic Cadence',
        'progressionLibrarySlug' => 'perfect-authentic-cadence',
        'progressionSeedKey' => 'A',
        'progressionCaption' => "Although the <strong>minor ii-V</strong> appears repeatedly in jazz renditions of <em>Manhã de Carnaval</em>, Luiz Bonfá used a simple, classical progression in his wonderful arrangement.",
        'progressionSlugs' => ['m7b5-drop2-roota', 'dom7-shell-roote'],
        // Live leadsheet bars — replaces progressionTiles in the SyncedPlayer panel
        'syncedPlayer' => ['slug' => 'manha-de-carnaval', 'start' => 1, 'end' => 3],
        'rhythmName' => 'Trademark Rhythm Pattern',
        'rhythmSlug' => 'bonfa',
        'rhythmCaption' => "<strong>Luiz Bonfá's</strong> favourite pattern is so simple yet effective. The thumb plays a steady bass while the fingers pluck the upper strings in a gentle, flowing rhythm.",
        'rhythmCitation' => "<strong>Luiz Bonfá</strong>, <em>Solo In Rio</em>, 1959",
        'relatedProducts' => [
            [
                'title' => 'Bossa Nova Basics',
                'description' => 'Learn the fundamentals of Bossa Nova guitar — rhythms, chord shapes, and a first song.',
                'url' => '/learn/bossa-nova-basics',
                'type' => 'course',
            ],
            [
                'title' => 'Music Theory Basics',
                'description' => 'Understand the harmony behind Bossa Nova — intervals, chord construction, and how progressions work.',
                'url' => '/learn/music-theory-basics',
                'type' => 'course',
            ],
        ]
    ],
    'corcovado' => [
        'title' => 'Corcovado',
        'shortTitle' => 'Corcovado',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/3.webp',
        'description' => "Jobim named this song after the <em>Corcovado</em> mountain in Rio de Janeiro — the peak crowned by the Christ the Redeemer statue — and the music carries the silence of that high place at night: hushed, intimate, suspended. <strong>Astrud Gilberto's</strong> vocal on <em>Getz/Gilberto</em> (1964) made \"Quiet Night of Quiet Stars\" one of the most tender recordings in jazz and bossa nova history.",
        'recordings' => '651 Recordings',
        'voicingName' => 'Key Chords',
        'voicingSlug' => 'm6-drop3-roote',
        'rootOverride' => 'A',
        'voicingCaption' => "The <strong>Am6</strong> chord anchors the root on the E-string. It is one of the TOP10 Bossa Nova chords and a fundamental part of the Bossa Nova and Jazz sound.",
        'progressionName' => 'The Corcovado Progression',
        'progressionLibrarySlug' => 'the-corcovado-progression',
        'progressionSeedKey' => 'A',
        'progressionCaption' => "Together the <strong>Am6</strong> and <strong>G#dim7</strong> form the <strong>Line Cliché</strong> at the heart of <em>Corcovado</em>. This chord motion — tonic colour shifting into passing dissonance — is the sound of <strong>saudade</strong> on the guitar.",
        'progressionSlugs' => ['m6-drop3-roota', 'o7-drop3-roota'],
        // Live leadsheet bars — replaces progressionTiles in the SyncedPlayer panel
        'syncedPlayer' => ['slug' => 'corcovado', 'start' => 0, 'end' => 7],
        'rhythmName' => 'Trademark Rhythm Pattern',
        'rhythmSlug' => 'extended-gilberto-rhythm',
        'rhythmCaption' => "<strong>João Gilberto</strong> played many variations in his rhythm patterns. This is a simple extension of the basic pattern.",
        'rhythmCitation' => "<strong>João Gilberto</strong>, <em>O Amor, O Sorriso E A Flor</em>, 1960",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Ten essential Bossa Nova guitar chords with voicing diagrams, practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ]
    ],
    'how-insensitive' => [
        'title' => 'How Insensitive',
        'shortTitle' => 'How Insensitive',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/6.webp',
        'description' => "The Portuguese title <em>Insensatez</em> means \"foolishness\" — Jobim wrote it as a lament for a love handled badly, and the English adaptation \"How Insensitive\" perfectly captures the same self-reproach. The chromatic descending bass line echoes the Corcovado tradition, but here it moves slower, heavier — a favourite ballad vehicle for jazz improvisers ever since <strong>Stan Getz</strong> recorded it on <em>Getz/Gilberto</em>.",
        'recordings' => '556 Recordings',
        'voicingName' => 'Key Chords',
        'voicingSlug' => 'o7-drop3-roote-b13',
        'rootOverride' => 'Bb',
        'voicingCaption' => "This <strong>Dominant 7</strong> voicing is enriched with the colour tone b13. The b13 is a common alteration in Jobim's ballads, giving the chords a darker, more melancholic sound that perfectly suits the mood of <em>Insensatez</em>.",
        'progressionName' => 'Minor Blues Cadenza',
        'progressionLibrarySlug' => 'minor-blues-cadenza',
        'progressionSeedKey' => 'B',
        'progressionCaption' => "The Minor Blues Cadenza in <em>Insensatez</em> features a distinctive harmonic movement. The voicings here are rooted in the minor blues tradition but are coloured with Jobim's unique harmonic language, including the use of the b13 for added tension and emotional depth.",
        // Live leadsheet bars — Gmaj7(#11) F#7 Bm7 progression at the end
        'syncedPlayer' => ['slug' => 'insensatez', 'start' => 4, 'end' => 11],
        'rhythmName' => 'Trademark Rhythm Pattern',
        'rhythmSlug' => 'insensatez',   
        'rhythmCaption' => "<strong>João Gilberto's</strong> recording of <em>Insensatez</em> features an interesting rhythm pattern. Like the clave patterns of Cuba, it dominates the song, dictating the flow of the music.",
        'rhythmCitation' => "<strong>João Gilberto</strong>, <em>João Gilberto</em>, 1961",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Ten essential Bossa Nova guitar chords with voicing diagrams, practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ]
    ],
    'wave' => [
        'title' => 'Wave',
        'shortTitle' => 'Wave',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/9.webp',
        'description' => "Since its first recording in 1967, <em>Wave</em> has been a favourite of both bossa nova and jazz musicians. Jobim built a sophisticated descending bass line beneath the melody and structured the first section as a loose blues — a rare convergence that made the song irresistible to improvisers. The intro's triad-over-bass technique is one of the most distinctive moments in Brazilian guitar writing.",
        'recordings' => '488 Recordings',
        'voicingName' => 'Key Chord',
        'voicingSlug' => 'm7-shell-roota-9',
        'rootOverride' => 'D',
        'voicingCaption' => "This Dm7(9) chord is a perfect fit for the introduction to Wave.",
        'progressionName' => 'The Jazz Half Cadence',
        'progressionLibrarySlug' => 'the-jazz-half-cadence',
        'progressionSeedKey' => 'C',
        'progressionCaption' => "The <strong>Jazz Half Cadence</strong> sets up the rhythm for Wave, sustaining tension before the melody appears.",
        'progressionSlugs' => ['min7-shell-roote', 'min7-shell-roote'],
        // Live leadsheet bars — Wave bars 0-1
        'syncedPlayer' => ['slug' => 'wave', 'start' => 0, 'end' => 1],
        'rhythmName' => 'The "Wave" Syncopation',
        'rhythmSlug' => 'partido-alto',
        'rhythmCaption' => "<em>Wave</em> uses a rhythm often linked to the <strong>\"Partido Alto\"</strong> style. Note the anticipation: the chord attacks often land on the weak off-beats.",
        'rhythmCitation' => "<strong>Antonio Carlos Jobim</strong>, <em>Wave</em>, 1967",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Ten essential Bossa Nova guitar chords with voicing diagrams, practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ]
    ],
    'one-note-samba' => [
        'title' => 'One Note Samba',
        'shortTitle' => 'One Note Samba',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/8.webp',
        'description' => "The melody truly does return to a single repeated note — and yet the song never feels static, because beneath it <strong>Jobim</strong> builds a cascading sequence of <strong>tritone substitutions</strong> that draws jazz musicians like few bossa nova tunes do. Recorded by <strong>João Gilberto</strong> in 1960 on <em>O Amor, O Sorriso E A Flor</em>, it quickly became a jam-session staple for its rapid chord changes at medium-up tempos.",
        'recordings' => '476 Recordings',
        'voicingName' => 'Key Chord',
        'voicingSlug' => 'm7-shell-roote',
        'rootOverride' => 'B',
        'voicingCaption' => "The three-note <strong>shell voicing</strong> — root, 7th and 3rd — is the practical key to <em>One Note Samba</em>: the changes move fast and the melody note sits on top of the shape. Lock in this <strong>Bm7</strong> frame and the subsequent chords will fall naturally under the fingers.",
        'progressionName' => 'Tritone Substitution Jazz Cadence',
        'progressionLibrarySlug' => 'tritone-substitution-jazz-cadence',
        'progressionSeedKey' => 'Ab',
        'progressionCaption' => "The <strong>Tritone Substitution</strong> is an advanced jazz concept that replaces the expected dominant chord with one a tritone away. In <em>One Note Samba</em> this produces a smooth chromatic bass descent while the melody holds its ground on a single pitch.",
        'progressionSlugs' => ['m7-shell-roote', 'dom7-shell-roote', 'm7-shell-roote'],
        // Live leadsheet bars — One Note Samba bars 1-4
        'syncedPlayer' => ['slug' => 'one-note-samba', 'start' => 0, 'end' => 3],
        'rhythmName' => 'Trademark Rhythm Pattern',
        'rhythmSlug' => 'partido-alto',
        'rhythmCaption' => "The <strong>Partido Alto</strong> is a traditional Brazilian rhythm pattern that underpins many samba and bossa nova songs.",
        'rhythmCitation' => "<strong>Quincy Jones</strong>, <em>Big Band Bossa Nova</em>, 1962",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
        ]
    ],
    'aquarela-do-brasil' => [
        'title' => 'Aquarela do Brasil',
        'shortTitle' => 'Brasil',
        'artist' => 'Ary Barroso',
        'image' => '/images/top10/bossa-nova-songs/1.webp',
        'description' => "<em>Aquarela do Brasil</em> is one of the great samba anthems — composed by <strong>Ary Barroso</strong> in 1939 and first recorded by <strong>Francisco Alves</strong> that same year. Unlike the cool introspection of <strong>bossa nova</strong>, this is <strong>samba</strong> in full celebration: big melody, driving rhythm, and the most famous descending <strong>Line Cliché</strong> in Brazilian music — a bass-voice sequence every guitarist must have under their fingers.",
        'recordings' => '435 Recordings',
        'voicingName' => 'Key Chord',
        'voicingSlug' => 'add9-archetype-roote',
        'rootOverride' => 'G',
        'voicingCaption' => "This <strong>G(add9)</strong> chord is one of the most basic chords. From this starting position, the inner voice moves chromatically through the rest of the Line Cliché without requiring a dramatic shift in hand position.",
        'progressionName' => 'The Samba Line Cliché',
        'progressionCaption' => "The <strong>Samba Line Cliché</strong> keeps the tonic chord rooted while an inner voice moves one semitone at a time. A simple mechanism with a dramatically emotional effect.",
        'progressionSlugs' => ['maj7-shell-roote', 'maj7-shell-roote', 'maj6-shell-roote'],
        // Live leadsheet bars — Aquarela do Brasil bars 0-3
        'syncedPlayer' => ['slug' => 'aquarela-do-brasil', 'start' => 0, 'end' => 3],
        'rhythmName' => 'Trademark Rhythm Pattern',
        'rhythmSlug' => 'samba-brasil',
        'rhythmCaption' => "Another iconic rhythm: this Samba rhythm has a wonderful symmetry of three strong and three weak beat accents.",
        'rhythmCitation' => "<em>Aquarela do Brasil</em>, <strong>Francisco Alves</strong>, 1939",
        'relatedProducts' => [
            [
                'title' => 'Music Theory Basics',
                'description' => 'Understand the harmony behind Bossa Nova — intervals, chord construction, and how progressions work.',
                'url' => '/learn/music-theory-basics',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Basics',
                'description' => 'Learn the fundamentals of Bossa Nova guitar — rhythms, chord shapes, and a first song.',
                'url' => '/learn/bossa-nova-basics',
                'type' => 'course',
            ],
        ]
    ],
    'desafinado' => [
        'title' => 'Desafinado',
        'shortTitle' => 'Desafinado',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/4.webp',
        'description' => "When critics dismissed Bossa Nova as \"out of tune,\" Tom Jobim answered with <em>Desafinado</em> — a song whose title literally means \"Slightly Out of Tune.\" The harmony makes the joke flesh: the dissonant <strong>#11</strong> on the secondary dominant is precisely the \"wrong\" note the critics complained about, and here it is the point of the whole song. The <strong>Stan Getz & João Gilberto</strong> recording on <em>Getz/Gilberto</em> (1964) turned this wry retort into a worldwide hit.",
        'recordings' => '424 Recordings',
        'voicingName' => 'Key Chord',
        'voicingSlug' => 'dom7-drop3-roote-13',
        'rootOverride' => 'E',
        'voicingCaption' => "The title <em>Desafinado</em> translates to \"Slightly Out of Tune.\" This effect is achieved by the <strong>Secondary Dominant (<strong>II7</strong>)</strong>. Joao Gilberto choses a simple E7 chord without any alteration.",
        'progressionName' => 'The Ascending Diminished Progression',
        'progressionLibrarySlug' => 'ascending-diminished',
        'progressionSeedKey' => 'F',
        'progressionCaption' => "<em>Desafinado</em> modulates to different keys, this excerpt is from the middle section in the key of <strong>A</strong> — the <strong>Ascending Diminished Progression</strong> just like Joao Gilberto does in the recording.",
        'progressionVoicingOverrides' => [
            2 => 'dom7-drop3-roote-s11',
        ],
                 // Live leadsheet bars — desafinado bars 36-39
        'syncedPlayer' => ['slug' => 'desafinado', 'start' => 36, 'end' => 39],
        'rhythmName' => 'Syncopated Phrasing',
        'rhythmSlug' => 'desafinado',
        'rhythmCaption' => "The melody of <em>Desafinado</em> is famous for starting on the \"and\" of beats. Your guitar accompaniment should be steady to support the \"stumbling\" vocal melody.",
        'rhythmCitation' => "<strong>Stan Getz & João Gilberto</strong>, <em>Getz / Gilberto</em>, 1964",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
        ]
    ],
    'chega-de-saudade' => [
        'title' => 'Chega De Saudade',
        'shortTitle' => 'Chega de Saudade',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/2.webp',
        'description' => "\"No More Blues\" — yet the title is ironic: <em>saudade</em> is the untranslatable Portuguese word for a bittersweet longing that never truly disappears. <strong>João Gilberto's</strong> 1958 recording is widely regarded as the <strong>birth of Bossa Nova</strong>: the cool, introverted guitar style and the fusion of samba rhythm with jazz harmony crystallised in a single track. The chord changes here represent the harmonic heart of the genre.",
        'recordings' => '404 Recordings',
        'voicingName' => 'Key Chord',
        'voicingSlug' => 'o7-drop3-roote',
        'rootOverride' => 'B',
        'voicingCaption' => "This chord is one of the most important in the Bossa Nova vocabulary. The diminished 7th chord is a common passing chord but also works as a dominant chord with b9.",
        'progressionName' => 'Secondary Dominant Cadence',
        'progressionLibrarySlug' => 'secondary-dominant-ii-v',
        'progressionSeedKey' => 'Dm',
        'progressionCaption' => "The <strong>Secondary Dominant Cadence</strong> captures the tension-and-release core of <em>Chega de Saudade</em>. Although the song features some interesting passing chords, the main harmonic motion is a simple.",
        // Live leadsheet bars — Chega de Saudade bars 8-15
        'syncedPlayer' => ['slug' => 'chega-de-saudade', 'start' => 8, 'end' => 15],
        'rhythmName' => 'The Original Beat',
        'rhythmSlug' => 'gilberto-rhythm',
        'rhythmCaption' => "This track introduced the famous \"stutter\" or syncopation that imitates the Brazilian samba percussion (the Tamborim) on the guitar strings.",
        'rhythmCitation' => "<strong>João Gilberto</strong>, <em>João Voz E Violão</em>, 2000",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
        ]
    ],
    'dindi' => [
        'title' => 'Dindi',
        'shortTitle' => 'Dindi',
        'artist' => 'Tom Jobim',
        'image' => '/images/top10/bossa-nova-songs/10.webp',
        'description' => "<em>Dindi</em> is one of Jobim's most intimate ballads — a love poem addressed to the sky, the wind, and a faraway beloved. <strong>Astrud Gilberto's</strong> 1965 recording on <em>The Astrud Gilberto Album</em> introduced it to international audiences with characteristic tenderness. The opening sequence — a slow descent through major and minor seventh chords — makes it an ideal piece for developing a singing, legato touch on the guitar.",
        'recordings' => '386 Recordings',
        'voicingName' => 'Key Chord',
        'voicingSlug' => 'maj7-drop2-roota',
        'rootOverride' => 'C',
        'voicingCaption' => "This Major7 voicing has to be a part of every guitarist's repertoire. In Dindi, you can play the first bars just by sliding this chord down 2 frets.",
        'progressionName' => 'Modal Interchange in C',
        'progressionLibrarySlug' => 'modal-interchange',
        'progressionSeedKey' => 'C',
        'progressionCaption' => "<em>Dindi</em> blooms with a classic <strong>modal interchange</strong> color. The BbMaj7 is part of the minor mode on the 5th degree.",
        // Live leadsheet bars — Dindi bars 0-1
        'syncedPlayer' => ['slug' => 'dindi', 'start' => 0, 'end' => 1],
        'rhythmName' => 'Ballad Bossa Pattern',
        'rhythmSlug' => 'bonfa',
        'rhythmCaption' => "<em>Dindi</em> floats. Use this slower pattern with more sustain to create that dreamy atmosphere.",
        'rhythmCitation' => "<strong>Astrud Gilberto</strong>, <em>The Astrud Gilberto Album</em>, 1965",
        'relatedProducts' => [
            [
                'title' => 'Gilberto plays Jobim',
                'description' => 'Learn the exact chord voicings and rhythms João Gilberto used on the Getz/Gilberto recording.',
                'url' => '/learn/gilberto-plays-jobim',
                'type' => 'course',
            ],
            [
                'title' => 'Bossa Nova Chords',
                'description' => 'Master the essential chord shapes and extensions that define the Bossa Nova sound.',
                'url' => '/learn/bossa-nova-chords-ii',
                'type' => 'course',
            ],
        ]
    ]
];
