<?php

return [
    'maj6-custom-roote-inv2-9' => [
        'title' => 'The Major 6/9 Chord',
        'shortTitle' => 'Major 6/9',
        'chordName' => 'Db6/9/Ab',
        'rootOverride' => 'Db',
        'image' => '/images/top10/bossa-chords/1.jpg',
        'description' => "This is THE iconic sound from the Getz/Gilberto recording — the chord that made Bossa Nova famous worldwide. Despite its complex name, this major 6/9 voicing defines the smooth, lush character that captured global attention.",
        'voicingCaption' => "João Gilberto loved to play the 5th in the bass — this is the quintessential bossa nova chord, as heard in the beginning of \"The Girl from Ipanema\" on the famous Getz/Gilberto recording.",
        'progressionName' => 'Trademark Chord Progression',
        'progressionViewerName' => 'Ellington Progression',
        'progressionLibrarySlug' => 'ellington-progression',
        'progressionSeedKey' => 'Db',
        'progressionVoicingOverrides' => [
            0 => 'maj6-custom-roote-inv2-9',
        ],
        'progressionCaption' => 'The Ellington movement I -> II7 is shown here in Db, with Db6/9/Ab pinned as the tonic I voicing.',
        // Live leadsheet bars — same as Bossa Nova Songs Girl from Ipanema
        'syncedPlayer' => ['slug' => 'the-girl-from-ipanema', 'start' => 5, 'end' => 12],
        'relatedProducts' => [
            [
                'title' => 'The Girl from Ipanema',
                'description' => "This transcription accurately captures the chords performed by Joao Gilberto on the 'Getz/Gilberto' recording.",
                'url' => '/shop/product/the-girl-from-ipanema',
                'type' => 'product',
            ],
        ],
    ],
    'm7-shell-roota-9' => [
        'title' => 'Minor Seventh with 9',
        'shortTitle' => 'm7(9)',
        'chordName' => 'Cm7(9)',
        'rootOverride' => 'C',
        'image' => '/images/top10/bossa-chords/2.jpg',
        'description' => 'The little sister of the Major 9 chord — a bit more mellow and at least as beautiful. Essential for the smooth Bossa Nova sound.',
        'voicingCaption' => 'A lush minor chord with the 9th on top, perfect for the smooth "Blue Bossa" sound.',
        'progressionName' => 'Trademark Chord Progression',
        'progressionLibrarySlug' => 'the-minor-jazz-cadence',
        'progressionSeedKey' => 'Cm',
        'progressionVoicingOverrides' => [
            2 => 'm7-shell-roota-9',
        ],
        'progressionCaption' => 'A minor II-V-I in C minor with Cm7(9) shell-rootA pinned as Im.',
        // Live leadsheet bars — Blue Bossa
        'syncedPlayer' => ['slug' => 'untitled-8', 'start' => 0, 'end' => 7],
        'relatedProducts' => [
            [
                'title' => 'Blue Bossa',
                'description' => 'Blue Bossa, a Latin-Jazz classic, is one of the most frequently performed jazz bossa tunes and a popular choice for jam sessions and improvisations.',
                'url' => '/shop/product/blue-bossa',
                'type' => 'product',
            ],
        ],
    ],
    'm6-drop3-roote' => [
        'title' => 'The Minor Sixth Chord',
        'shortTitle' => 'm6',
        'chordName' => 'Am6',
        'rootOverride' => 'A',
        'image' => '/images/top10/bossa-chords/3.jpg',
        'description' => "The minor 6th chord is the darker, more mysterious alternative to the minor 7th chord. Perfect as a tonic chord for Jazz and Bossa Nova ballads like 'Corcovado'.",
        'voicingCaption' => 'A dark tonic chord that provides the signature resolution for "Corcovado."',
        'progressionName' => 'Trademark Chord Progression',
        'progressionLibrarySlug' => 'the-corcovado-progression',
        'progressionSeedKey' => 'A',
        'progressionVoicingOverrides' => [
            0 => 'm6-drop3-roote',
        ],
        'progressionCaption' => 'The Corcovado progression in A minor with Am6 pinned as the Im key chord.',
        // Live leadsheet bars — Corcovado A section
        'syncedPlayer' => ['slug' => 'untitled-6', 'start' => 1, 'end' => 8],
        'relatedProducts' => [
            [
                'title' => 'Corcovado',
                'description' => "This transcription of João Gilbertos chords to 'Corcovado' includes a simplified arrangement in the same key.",
                'url' => '/shop/product/corcovado-joao-gilberto',
                'type' => 'product',
            ],
        ],
    ],
    'dom7-drop3-roote-13' => [
        'title' => 'Dominant Seventh with 13',
        'shortTitle' => '7(13)',
        'chordName' => 'G7(13)',
        'rootOverride' => 'G',
        'image' => '/images/top10/bossa-chords/4.jpg',
        'description' => "A complicated name for a simple, elegant sound. Often used in typical chord progressions for Latin tunes like Jobim's 'Wave'.",
        'voicingCaption' => 'A colorful dominant seventh chord used extensively in Jobim\'s "Wave."',
        'progressionName' => 'Trademark Chord Progression',
        'progressionViewerName' => 'The Major Jazz Cadence',
        'progressionLibrarySlug' => 'minor-ii-v-to-major',
        'progressionSeedKey' => 'C',
        'progressionVoicingOverrides' => [
            1 => 'dom7-drop3-roote-13',
        ],
        'progressionCaption' => 'A major II-V-I in C major (Dm7 -> G7 -> Cmaj7), linked from the DB progression library, with G7(13) pinned as V7.',
        // Live leadsheet bars — Wave first 2 bars
        'syncedPlayer' => ['slug' => 'untitled-7', 'start' => 0, 'end' => 1],
        'relatedProducts' => [
            [
                'title' => 'Wave',
                'description' => 'This is an advanced-level arrangement of Wave (original: Vou Te Contar) by Tom Jobim, arranged for solo guitar.',
                'url' => '/shop/product/wave',
                'type' => 'product',
            ],
        ],
    ],
    'm7b5-drop2-roota' => [
        'title' => 'The Half Diminished Chord',
        'shortTitle' => 'm7b5',
        'chordName' => 'Bm7b5',
        'rootOverride' => 'B',
        'image' => '/images/top10/bossa-chords/5.jpg',
        'description' => "As part of a II-V-I cadence in minor, the half-diminished chord (m7b5) is an essential building block of Jazz and Bossa Nova songs.",
        'voicingCaption' => 'The vital "ii" chord for minor cadences in classics like "Manha de Carnaval."',
        'progressionName' => 'Trademark Chord Progression',
        'progressionViewerName' => 'The Minor Jazz Cadence',
        'progressionLibrarySlug' => 'the-minor-jazz-cadence',
        'progressionSeedKey' => 'Cm',
        'progressionVoicingOverrides' => [
            0 => 'm7b5-drop2-roota',
        ],
        'progressionCaption' => 'A minor II-V-I in A minor with the key chord pinned as IIm7b5.',
        'relatedProducts' => [
            [
                'title' => 'The Gentle Rain',
                'description' => 'This is an original solo guitar arrangement of the fascinating song by Luiz Bonfá.',
                'url' => '/shop/product/the-gentle-rain',
                'type' => 'product',
            ],
        ],
    ],
    'dom7-shell-roota-9' => [
        'title' => 'Dominant Seventh with 9',
        'shortTitle' => '7(9)',
        'chordName' => 'C7(9)',
        'rootOverride' => 'C',
        'image' => '/images/top10/bossa-chords/8.jpg',
        'description' => "Dominant Seventh chords are vital to any music genre. The Dom7(9) version is common in Latin-song intros like 'Oye Como Va'.",
        'voicingCaption' => 'A versatile, open-sounding dominant often used in both Bossa and Latin Blues.',
        'progressionName' => 'Trademark Chord Progression',
        'progressionViewerName' => 'Ascending Diminished',
        'progressionLibrarySlug' => 'ascending-diminished',
        'progressionSeedKey' => 'C',
        'progressionVoicingOverrides' => [
            1 => 'dom7-shell-roota-9',
        ],
        'progressionCaption' => 'Ascending Diminished in C, with C7(9) featured as a key dominant color.',
        'relatedProducts' => [
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Here is the PDF that goes with this list. It shows ten of the most famous bossa nova guitar chords, along with practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ],
    ],
    'dom7-shell-roota-b9' => [
        'title' => 'Dominant Seventh with b9',
        'shortTitle' => '7(b9)',
        'chordName' => 'E7(b9)',
        'rootOverride' => 'E',
        'image' => '/images/top10/bossa-chords/6.jpg',
        'description' => "Along with the half-diminished chord, the Dom7b9 forms the 'minor cadence' team. Adds dramatic tension and release.",
        'voicingCaption' => 'Adds a beautiful tension that resolves perfectly to a minor tonic.',
        'progressionName' => 'Trademark Progression',
        'progressionCaption' => 'A high-tension minor turnaround.',
        'progressionSlugs' => ['m7-drop2-roota', 'dom7-shell-roota-b9', 'maj6-shell-roota-9'],
        'progressionRoots' => ['B', 'E', 'A'],
        'relatedProducts' => [
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Here is the PDF that goes with this list. It shows ten of the most famous bossa nova guitar chords, along with practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ],
    ],
    'o7-drop2-roota' => [
        'title' => 'The Diminished Seventh Chord',
        'shortTitle' => 'dim7',
        'chordName' => 'C#dim7',
        'rootOverride' => 'C#',
        'image' => '/images/top10/bossa-chords/7.jpg',
        'description' => "The 'Secret Weapon' of Bossa Nova! Tom Jobim used diminished chords in numerous songs as smooth passing harmonies.",
        'voicingCaption' => "Jobim's secret weapon for chromatic passing chords between major and minor.",
        'progressionName' => 'Trademark Chord Progression',
        'progressionViewerName' => 'Ascending Diminished',
        'progressionLibrarySlug' => 'ascending-diminished',
        'progressionSeedKey' => 'C',
        'progressionVoicingOverrides' => [
            1 => 'o7-drop2-roota',
        ],
        'progressionCaption' => 'Ascending Diminished in C, with the key chord pinned on the diminished slot (#Idim7).',
        'relatedProducts' => [
            [
                'title' => 'How Insensitive',
                'description' => 'How Insensitive is packed with diminished chords. This lovely solo guitar arrangement is modelled on João Gilbertos recording of O Amor, o Sorriso e a Flor.',
                'url' => '/shop/product/how-insensitive',
                'type' => 'product',
            ],
        ],
    ],
    'o7-drop3-roote-b13' => [
        'title' => 'Diminished with Flat 13',
        'shortTitle' => 'o7(b13)',
        'chordName' => 'G#dim7(b13)',
        'rootOverride' => 'G#',
        'image' => '/images/top10/bossa-chords/9.jpg',
        'description' => "To make a diminished chord softer, add a b13. This voicing was a favorite of Joao Gilberto, used in his treatment of 'Corcovado'.",
        'voicingCaption' => 'The signature "João Gilberto" voicing that softens the diminished sound.',
        'progressionName' => 'Trademark Chord Progression',
        'progressionViewerName' => 'Corcovado Progression',
        'progressionLibrarySlug' => 'the-corcovado-progression',
        'progressionSeedKey' => 'A',
        'progressionVoicingOverrides' => [
            1 => 'o7-drop3-roote-b13',
        ],
        'progressionCaption' => 'Corcovado progression with the signature diminished color in an A-minor setting.',
        'relatedProducts' => [
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Here is the PDF that goes with this list. It shows ten of the most famous bossa nova guitar chords, along with practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ],
    ],
    'dom7-drop3-roote-b13' => [
        'title' => 'Dominant Seventh with b13',
        'shortTitle' => '7(b13)',
        'chordName' => 'G7(b13)',
        'rootOverride' => 'G',
        'image' => '/images/top10/bossa-chords/10.jpg',
        'description' => "Used to create a strong tension effect that typically resolves to a major chord, as heard in the beautiful 'How Insensitive'.",
        'voicingCaption' => 'High tension dominant voicing, ideal for moving toward a major resolution.',
        'progressionName' => 'Trademark Chord Progression',
        'progressionViewerName' => 'The Minor Jazz Cadence',
        'progressionLibrarySlug' => 'the-minor-jazz-cadence',
        'progressionSeedKey' => 'Cm',
        'progressionVoicingOverrides' => [
            1 => 'dom7-drop3-roote-b13',
        ],
        'progressionCaption' => 'A minor II-V-I in C minor with the key chord pinned on the V7 slot as G7(b13).',
        'relatedProducts' => [
            [
                'title' => 'TOP10 Bossa Nova Chords',
                'description' => 'Here is the PDF that goes with this list. It shows ten of the most famous bossa nova guitar chords, along with practice patterns and song examples.',
                'url' => '/shop/product/top10-bossa-nova-chords',
                'type' => 'product',
            ],
        ],
    ],
];
