<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Retire the hand-authored diminished-7th alias rows that are now GENERATED at
 * runtime from the DiminishedSymmetry primitive:
 *
 *   - dim7 inversion aliases (alt_quality = o7) → generated by
 *     ChordLibraryController::buildDiminishedReadings (the four inversions).
 *   - bare dom7(b9) aliases (alt_quality = dom7, alt_extensions = 'b9') →
 *     generated for the Show page (buildDiminishedReadings aliases) and for
 *     search (ChordVoicingSearch::findDiminishedDominantMatches).
 *
 * Only these two categories on `o7` parents are removed. Aliases carrying extra
 * tensions the bare dim shape can't voice (e.g. b9,13 or #9) are LEFT in place —
 * the generators don't claim those exact extensions, so they'd otherwise vanish.
 *
 * Non-destructive to behaviour: the readings are recomputed on every page load /
 * search, so removing the stored rows changes nothing the user sees except that
 * ALL dim7 shapes now surface consistently (previously only the 2 hand-annotated
 * shapes did, with duplicate rows).
 */
return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('sbn_chord_diagram_aliases') || ! Schema::hasTable('sbn_chord_diagrams')) {
            return;
        }

        $o7Ids = DB::table('sbn_chord_diagrams')->where('quality', 'o7')->pluck('id');
        if ($o7Ids->isEmpty()) {
            return;
        }

        DB::table('sbn_chord_diagram_aliases')
            ->whereIn('diagram_id', $o7Ids)
            ->where(function ($q) {
                // dim7 inversion aliases
                $q->where('alt_quality', 'o7')
                    // bare dom7(b9) aliases (exactly 'b9', not b9,13 / b9#11 / #9)
                    ->orWhere(function ($q2) {
                        $q2->where('alt_quality', 'dom7')->where('alt_extensions', 'b9');
                    });
            })
            ->delete();
    }

    public function down(): void
    {
        // Irreversible: these rows are now generated at runtime and intentionally
        // not stored. No data is lost behaviourally.
    }
};
